apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-wp-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-webserver
  template:
    metadata:
      labels:
        app: my-webserver
    spec:
      containers:
      - name: apache-wp
        image: apache-wp
        ports:
        - containerPort: 80
