apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-wp-ingress
spec:
  rules:
  - host: ${webAddress}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache-wp-svc
            port:
              number: ${svcPort}